### ISSUE TITLE
Add more information to the Studierendenhaus description

### ISSUE THREAD

**Issue by alexhorn** [neuland-ingolstadt/orientierungsphase#3]
Maybe we could include a list of all student clubs at the THI.

**Comment by FabianSimonGross** [comment]
Why don't we link it back to this Page?

Like: What are clubs at the THI at the moment? Find out more here: https://www.thi.de/studium/studentisches-leben/studentische-vereine-an-der-thi

**Comment by FabianSimonGross** [comment]
Can't we actually close this?
